[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"
